- name: Install gdown using apt
  shell: "pip install gdown"

- name: Creates directory
  file:
    path: /tmp/{{ work_dir }}
    state: directory

- name: download folder with data
  shell: "cd {{ work_dir }} && gdown https://drive.google.com/uc?id=1SFL-gYzu9RIIDFY4uBt-_TamHHmfROVG && tar -xzvf folder_test.tar.gz && rm folder_test.tar.gz"

- name: Pull default Docker image
  docker_image:
    name: "{{ default_container_image }}"
    source: pull

- name: Create default containers
  docker_container:
    detach: false
    name: "{{ default_container_name }}"
    image: "{{ default_container_image }}"
    command: "{{ default_container_command }}"
    volumes:
      - "/tmp/{{ work_dir }}/folder_test:/data/folder_test"
    state: started
  when: run=="true"